# Generated by Django 3.2.9 on 2021-11-25 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_room', models.IntegerField(null=True)),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next1', to='BattleZone.player')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev1', to='BattleZone.player')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_code', models.IntegerField(primary_key=True, serialize=False)),
                ('room_admin', models.CharField(max_length=100)),
                ('no_of_questions', models.IntegerField(default=3)),
                ('date', models.DateField()),
                ('currentPlayersCount', models.IntegerField(default=0)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head', to='BattleZone.player')),
                ('tail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tail', to='BattleZone.player')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Occupation', models.CharField(choices=[('STU', 'Student'), ('PRO', 'Professional'), ('OTR', 'Other')], max_length=3)),
                ('PreferredProgrammingLanguage', models.CharField(choices=[('CPP', 'C++'), ('JAVA', 'Java'), ('PYTHON', 'Python')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
