# Generated by Django 3.2.9 on 2021-11-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BattleZone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='in_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BattleZone.room'),
        ),
    ]
