# Generated by Django 3.2.9 on 2021-11-11 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BattleZone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Occupation', models.CharField(choices=[('STU', 'Student'), ('PRO', 'Professional'), ('OTR', 'Other')], default='STU', max_length=3)),
                ('PreferredProgrammingLanguage', models.CharField(choices=[('CPP', 'C++'), ('JAVA', 'Java'), ('PYTHON', 'Python')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usr',
        ),
    ]
