# Generated by Django 3.2.9 on 2021-11-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BattleZone', '0004_rename_additionalinfo_personalinfo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_code', models.IntegerField(primary_key=True, serialize=False)),
                ('room_admin', models.CharField(max_length=100)),
                ('no_of_questions', models.IntegerField(default=3)),
                ('no_of_players', models.IntegerField(default=1)),
                ('date', models.DateField()),
            ],
        ),
    ]
